In [2]:
import pandas as pd

### Check data quality of raw artificial APC data

In [5]:
path = "../data/raw/artificial_hes_apc_202302_v1_full/artificial_hes_apc_202302_v1_full/artificial_hes_apc_2122.csv"

NEEDED_COLS = [
    "PSEUDO_HESID", "EPIKEY", "EPIORDER",
    "ADMIDATE", "DISDATE", "ADMIMETH", "ADMISORC",
    "DIAG_4_01", "ETHNOS", "SEX", "STARTAGE", "LSOA11",
    "SPELBGIN", "SPELEND", "SPELDUR", "SPELDUR_CALC", "FYEAR",
]

raw_apc = pd.read_csv(
    path,
    usecols=NEEDED_COLS
)

raw_apc.head()

,FYEAR,EPIKEY,PSEUDO_HESID,ADMIDATE,ADMIMETH,ADMISORC,DIAG_4_01,DISDATE,EPIORDER,ETHNOS,SEX,SPELBGIN,SPELDUR,SPELDUR_CALC,SPELEND,STARTAGE,LSOA11
0,2122,811282731008,TESToBeA1ZCAwu96JtChcj174KEKSgD9,2021-03-31,11,19,K315,2021-06-22,1,A,2,0.0,0.0,2.0,Y,84.0,E01025529
1,2122,945889480421,TESToBeA1ZCAwu96JtChcj174KEKSgD9,2021-05-18,2D,19,K573,2021-06-16,1,A,2,2.0,0.0,0.0,Y,84.0,E01025463
2,2122,528111587051,TESTumS1fdRDx6j7yODr6lFffI5BZBDF,2021-05-15,24,19,I269,2021-05-27,1,A,2,0.0,4.0,2.0,Y,90.0,E01003625
3,2122,912335548721,TESTZhkl8wktpxboD3w4h9gznMl8EhMV,2021-04-28,11,19,I839,2021-06-11,1,A,2,2.0,0.0,0.0,Y,25.0,E01018984
4,2122,171243392039,TESTfJm3gvXDWqIhFLnKGYC07r5XTNNo,2021-04-27,25,19,N185,2021-04-27,1,A,1,2.0,0.0,1.0,Y,79.0,E01013736

From head above:
- Top rows above show incorrect spell duration and concurrent spells, which isn't expected. 
- E.g. for patient 'TESToBeA1ZCAwu96JtChcj174KEKSgD9':
    - Admitted on 2021-03-31 and discharged on 2021-06-22 but SPELDUR is shown as 0 days. 
    - Also, the same patient had another admission on 2021-05-18 and was discharged on 2021-06-16, which is before the spell listed above.

Next steps:
- Check episodes:spells for each patient (expect episodes count to be greater than spells count)
- Are there more records with concurrent spells? Consider fix.

In [7]:
dq = raw_apc.groupby("PSEUDO_HESID").agg(
    n_episodes=("EPIKEY","count"),
    n_unique_admissions=("ADMIDATE","nunique")
    ).query("n_episodes != n_unique_admissions")

dq.head(100)

                                  n_episodes  n_unique_admissions
PSEUDO_HESID
TEST005APsRAinbMVQEqYRZlkQGTBPSf           5                    4
TEST00QCRNHMSsT7KJpYtm1mNmoHM2BB           4                    3
TEST00VKt4YUKlttnI54HNpcC4D5v9Fi           2                    1
TEST00VU5rVZtZEY5TNLEYwZnJJA3cWH           4                    3
TEST00fXmHdJVQXNaRq4MS6BZOVLO1FJ           5                    4
...                                      ...                  ...
TEST0FTdr87FXEZyjIFjgTUhLLfXHRmb           2                    1
TEST0FXPoeTqkfKoyYXuXTmApNmOPIlF           5                    4
TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H           8                    7
TEST0Fh1v4OeL3FmHD8HbfrMHFZQxKDG           7                    6
TEST0Fm8rnIj2gN0bd9EBRaJrvie0qPK           3                    2

[100 rows x 2 columns]

In [9]:
raw_apc[raw_apc["PSEUDO_HESID"] == 'TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H'].sort_values(by=["ADMIDATE", "EPIORDER"])

,FYEAR,EPIKEY,PSEUDO_HESID,ADMIDATE,ADMIMETH,ADMISORC,DIAG_4_01,DISDATE,EPIORDER,ETHNOS,SEX,SPELBGIN,SPELDUR,SPELDUR_CALC,SPELEND,STARTAGE,LSOA11
124706,2122,516784941819,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,1801-01-01,11,19,J441,1801-01-01,1,A,1,0.0,21.0,3.0,Y,28.0,E01011012
124703,2122,910136965324,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-01,11,19,A099,2021-06-08,2,A,1,2.0,1.0,0.0,Y,28.0,W01000701
124702,2122,416580577649,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-07,12,19,K805,2021-06-20,1,A,1,0.0,1.0,3.0,Y,28.0,E01012718
124700,2122,712322910884,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-08,21,19,Z711,2021-06-06,1,A,1,2.0,3.0,0.0,Y,28.0,E01003269
124701,2122,298323311825,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-08,21,19,S224,2021-04-29,1,A,1,2.0,0.0,0.0,Y,28.0,E01001813
124707,2122,886071818456,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-14,21,19,R91X,2021-06-08,1,A,1,0.0,0.0,0.0,Y,28.0,E01003733
124705,2122,850470849824,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-16,21,19,O021,2021-06-16,1,A,1,0.0,0.0,1.0,Y,28.0,E01020942
124704,2122,83182458648,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-05-28,21,19,R69X,2021-06-30,1,A,1,0.0,14.0,3.0,Y,28.0,E01027697

In [22]:
raw_apc.loc[
    raw_apc["LSOA11"].str.startswith("W", na=False),
    "LSOA11"
].drop_duplicates()

41        W01001093
276       W01000315
1031      W01000255
1058      W01000484
1120      W01000896
            ...
988210    W01000240
989140    W01000013
990433    W01000091
991689    W01000039
992060    W01000153
Name: LSOA11, Length: 468, dtype: object

The code above shows that there are more episodes than unique admission dates, which is something we would expect. However, analysing some patient records shows that there are concurrent spells and inconsistent spell calculations.

This is due to the fact that this is synthetic data, and as the synthetic HES data documentation states, the data "does not preserve relationships between fields".

As a result, to build a usable analysis table, I will:
- Collapse to one row per spell, where a spell is defined by the unique combination of (patient, admission date, discharge date).
- Recalculate length of stay (LOS) from these dates.
- Compute the mode of primary diagnosis, ethnicity, and sex per spell (deterministic tie-break).
- Flag any emergency admission within the spell.
- Remove LSOA codes that start with W01 as those are for Wales. The IMD mapping table for deciles is only for England.
- Join deprivation (IMD) and use quintiles.
- Create a stable spell ID (patient|adm|dis) for downstream analysis.
- Treat implausible dates (e.g. < 1900) as missing before calculations.

/tools/repair_synthetic_hes.py runs this cleaning process an returns apc_clean.parquet.

In [34]:
df = pd.read_parquet("../data/processed/apc_clean.parquet")

Review data for patient _TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H_ after cleansing

In [33]:
df[df["patient_id"] == 'TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H'].sort_values(by=["adm", "dis"])

,patient_id,adm,dis,n_episodes,los_days,any_emerg,imd_quintile,primary_diag,ethnicity,sex,spell_id
29059,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-07,2021-06-20,1,75.0,False,4,K805,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-04-07|20...
2053111,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-08,2021-04-29,1,22.0,True,1,S224,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-04-08|20...
751748,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-08,2021-06-06,1,60.0,True,2,Z711,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-04-08|20...
1538968,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-14,2021-06-08,1,56.0,True,2,R91X,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-04-14|20...
2101115,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-04-16,2021-06-16,1,62.0,True,5,O021,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-04-16|20...
721653,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,2021-05-28,2021-06-30,1,34.0,True,5,R69X,A,1,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H|2021-05-28|20...
1194962,TEST0FYUNmUXWIyAiTpex1MLNfIPrC1H,NaT,NaT,1,NaN,False,3,None,NaN,NaN,<NA>

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2908710 entries, 0 to 2908709
Data columns (total 12 columns):
 #   Column        Dtype
---  ------        -----
 0   patient_id    object
 1   adm           datetime64[ns]
 2   dis           datetime64[ns]
 3   n_episodes    int64
 4   los_days      float64
 5   any_emerg     bool
 6   imd_quintile  Int64
 7   primary_diag  object
 8   ethnicity     category
 9   sex           category
 10  age           Int16
 11  spell_id      string
dtypes: Int16(1), Int64(1), bool(1), category(2), datetime64[ns](2), float64(1), int64(1), object(2), string(1)
memory usage: 197.0+ MB

In [36]:
df.describe()

,adm,dis,n_episodes,los_days,imd_quintile,age
count,2600511,2525100,2.908710e+06,2.525097e+06,2852596.0,2523945.0
mean,2020-05-28 09:51:08.569983744,2020-08-17 06:07:52.289891072,1.028018e+00,8.314393e+01,2.886231,534.861711
min,2017-08-02 00:00:00,2019-04-01 00:00:00,1.000000e+00,1.000000e+00,1.0,1.0
25%,2019-07-13 00:00:00,2019-12-21 00:00:00,1.000000e+00,3.000000e+00,2.0,37.0
50%,2020-06-16 00:00:00,2020-10-13 00:00:00,1.000000e+00,4.900000e+01,3.0,61.0
75%,2021-04-07 00:00:00,2021-04-26 00:00:00,1.000000e+00,1.390000e+02,4.0,78.0
max,2021-06-29 00:00:00,2021-06-30 00:00:00,3.200000e+01,7.250000e+02,5.0,7007.0
std,NaN,NaN,3.037542e-01,9.080372e+01,1.40952,1761.024998

In [30]:
df["imd_quintile"].unique()

<IntegerArray>
[1, 2, 4, <NA>, 5, 3]
Length: 6, dtype: Int64

In [38]:
for col in ["ethnicity", "sex", "age", "imd_quintile"]:
    print(f"{col}: {df[col].unique()}")

ethnicity: ['A', 'Z', 'H', 'N', '99', ..., 'B', 'P', 'R', 'E', NaN]
Length: 19
Categories (18, object): ['99' < 'A' < 'B' < 'C' ... 'P' < 'R' < 'S' < 'Z']
sex: ['1', '2', '9', '0', NaN]
Categories (4, object): ['0' < '1' < '2' < '9']
age: <IntegerArray>
[   9, 7006,   23,    7,   77,   90,   56,   44,   38,   28,
 ...
   98, 7002,  103,  101,  102,  119,  105,  106,  108,  107]
Length: 118, dtype: Int16
imd_quintile: <IntegerArray>
[1, 3, 5, 2, 4, <NA>]
Length: 6, dtype: Int64

In [ ]:
J00-J99