# **01 - Data Quality**

**Purpose:**  
This notebook explores the data quality of the synthetic HES data before and after the cleansing process.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

### __DQ Checks Pre-cleanse__

In [2]:
# Load raw artificial APC data (one year only)
path = "../data/raw/artificial_hes_apc_202302_v1_full/artificial_hes_apc_202302_v1_full/artificial_hes_apc_2122.csv"

USE_COLS = [
    "PSEUDO_HESID", "EPIKEY", "EPIORDER",
    "ADMIDATE", "DISDATE", "ADMIMETH", "ADMISORC",
    "DIAG_4_01", "ETHNOS", "SEX", "STARTAGE", "LSOA11",
    "SPELBGIN", "SPELEND", "SPELDUR", "SPELDUR_CALC", "FYEAR",
]

raw_apc = pd.read_csv(path, usecols=USE_COLS)
raw_apc.head()

,FYEAR,EPIKEY,PSEUDO_HESID,ADMIDATE,ADMIMETH,ADMISORC,DIAG_4_01,DISDATE,EPIORDER,ETHNOS,SEX,SPELBGIN,SPELDUR,SPELDUR_CALC,SPELEND,STARTAGE,LSOA11
0,2122,811282731008,TESToBeA1ZCAwu96JtChcj174KEKSgD9,2021-03-31,11,19,K315,2021-06-22,1,A,2,0.0,0.0,2.0,Y,84.0,E01025529
1,2122,945889480421,TESToBeA1ZCAwu96JtChcj174KEKSgD9,2021-05-18,2D,19,K573,2021-06-16,1,A,2,2.0,0.0,0.0,Y,84.0,E01025463
2,2122,528111587051,TESTumS1fdRDx6j7yODr6lFffI5BZBDF,2021-05-15,24,19,I269,2021-05-27,1,A,2,0.0,4.0,2.0,Y,90.0,E01003625
3,2122,912335548721,TESTZhkl8wktpxboD3w4h9gznMl8EhMV,2021-04-28,11,19,I839,2021-06-11,1,A,2,2.0,0.0,0.0,Y,25.0,E01018984
4,2122,171243392039,TESTfJm3gvXDWqIhFLnKGYC07r5XTNNo,2021-04-27,25,19,N185,2021-04-27,1,A,1,2.0,0.0,1.0,Y,79.0,E01013736

From head above:
- Incorrect spell durations and concurrent spells, which isn't expected. 
- E.g. for patient 'TESToBeA1ZCAwu96JtChcj174KEKSgD9':
    - Admitted on 2021-03-31 and discharged on 2021-06-22 but SPELDUR is shown as 0 days. 
    - Also, the same patient had another admission on 2021-05-18 and was discharged on 2021-06-16, which is before the spell listed above.

Next steps:
- Check episodes, admissions and spells for each patient (expect episodes to be more than spells)
- Are there more records with concurrent spells? Consider fix.

In [16]:
# Episode, admission, spell counts (for respiratory patients)
c = (
    raw_apc
    .assign(spell_begin=lambda d: d["SPELBGIN"].isin([1, 2]))
    .groupby(["PSEUDO_HESID", "DIAG_4_01"], as_index=False)
    .agg(
        n_episodes=("EPIKEY", "count"),
        n_unique_admissions=("ADMIDATE", "nunique"),
        n_spell_begin=("spell_begin", "sum")
    )
    .loc[lambda d:
         d["DIAG_4_01"].astype("string").str.startswith("J", na=False)
         & (d["n_episodes"] != d["n_spell_begin"])
         & d["n_spell_begin"] > 0
    ]
)

c.head(20)

,PSEUDO_HESID,DIAG_4_01,n_episodes,n_unique_admissions,n_spell_begin
3672,TEST0ESTu849rLXefV1OJZb6lI73YTHH,J181,2,2,1
8504,TEST0W6rL11Mo4MS2YZCiScZjsRkweHE,J960,2,2,1
20783,TEST1IARVGvFLj9ApcRxMaT0cuPiIVdv,J181,2,2,1
23462,TEST1T0t1EpfTwXHgZoIUDd6PdgwsBRW,J440,2,2,1
36838,TEST2JEwZco1j5KX19PwAvfC1RSbrt5J,J181,2,2,1
39983,TEST2VptK5mPaJPxYeiZV2md3EEG6mJB,J189,2,2,1
40227,TEST2WnKPJ9PdJWLodZDvomYUKY92AHK,J181,3,3,1
40654,TEST2YRHMYviY2c8OCm3oGfR6XoY3mIv,J441,2,2,1
46056,TEST2tyigwZGnCRViHy8HfXjokc0Kcj6,J181,2,2,1
60425,TEST3mJ7QVx4JdfqzlpBdYsW2Y7G72rn,J189,2,2,1
67045,TEST4C9cOId2fMVbMTUXZE1XAeX0Ow2y,J181,2,2,1
79716,TEST4zr5S1KtV0luQGWIPn2Oe0Sw0krW,J181,2,2,1
96011,TEST61TKqqqnvSmrpwus4l3pGBGZvnlB,J22X,2,2,1
101051,TEST6LVsY2KqtKQL20BYu6ItuOOdDSUE,J440,2,2,1
103775,TEST6WWdwPoR0wN6W6HH2ON4wQeAkg0y,J181,2,2,1
115891,TEST7HNb4tOby6uMUBvMqNOHUv6XCO0p,J459,2,2,1
116728,TEST7KjfKZNSalZBu0PQb0Qmmnvx3AzS,J440,2,2,1
120715,TEST7aQpb5IXtkdecHcaEkzYGZhcIMPX,J069,2,2,1
160602,TESTA5WcaXeLHIS2Lb2BOwDUZFaNQyV1,J181,3,3,2
161635,TESTA9sqeGFcaXGesFoQTayzO1pjjpub,J181,2,2,1

In [4]:
# Check example patient
raw_apc[raw_apc["PSEUDO_HESID"] == 'TEST0ESTu849rLXefV1OJZb6lI73YTHH'].sort_values(by=["ADMIDATE", "EPIORDER"])

,FYEAR,EPIKEY,PSEUDO_HESID,ADMIDATE,ADMIMETH,ADMISORC,DIAG_4_01,DISDATE,EPIORDER,ETHNOS,SEX,SPELBGIN,SPELDUR,SPELDUR_CALC,SPELEND,STARTAGE,LSOA11
945716,2122,198474600434,TEST0ESTu849rLXefV1OJZb6lI73YTHH,1801-01-01,21,19,T490,1801-01-01,1,A,2,0.0,0.0,8.0,Y,37.0,E01010960
945713,2122,580430327323,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-04-10,31,19,J181,2021-04-10,1,A,2,0.0,0.0,0.0,Y,37.0,E01006803
945717,2122,59979746470,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-04-13,31,19,O268,2021-05-07,1,A,2,2.0,0.0,3.0,Y,37.0,E01012131
945715,2122,640387536754,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-04-28,13,19,J181,2021-05-17,1,A,2,2.0,0.0,0.0,Y,37.0,E01000498
945714,2122,897110358713,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-06-03,21,19,K805,2021-06-09,1,A,2,2.0,0.0,1.0,Y,37.0,E01028383

The code above shows that there are more episodes than unique admission dates, which is something we would expect. However, analysing some patient records shows:
 - concurrent spells
 - inconsistent spell calculations
 - n_spell_begin is lower than n_unique_admissions which means not all unique admissions are recorded as their own spell

This is due to the fact that this is synthetic data, and as the synthetic HES data documentation states, the data "does not preserve relationships between fields".

In [5]:
# Data contains Wales' LSOA codes - to be removed
wales = raw_apc.loc[
    raw_apc["LSOA11"].str.startswith("W", na=False),
    "LSOA11"
].drop_duplicates()

wales

41        W01001093
276       W01000315
1031      W01000255
1058      W01000484
1120      W01000896
            ...
988210    W01000240
989140    W01000013
990433    W01000091
991689    W01000039
992060    W01000153
Name: LSOA11, Length: 468, dtype: object

In [6]:
# Check age, sex and ethnicity fields

# age - infant ages 7001 - 7007 (less than 1 years old) to be removed
age = raw_apc["STARTAGE"].value_counts() # drop_duplicates().sort_values()
infants = raw_apc["STARTAGE"].astype(str).loc[lambda x: x.str.startswith("700")].value_counts()

# sex - keep only 1 and 2
sex = raw_apc["SEX"].value_counts()

# ethnicity - map codes to descriptions
eth = raw_apc["ETHNOS"].value_counts()

age, infants, sex, eth

(STARTAGE
 74.0      19459
 75.0      18358
 7004.0    18197
 77.0      17783
 73.0      17303
           ...
 102.0        75
 104.0        25
 105.0         7
 107.0         2
 106.0         1
 Name: count, Length: 115, dtype: int64,
 STARTAGE
 7004.0    18197
 7001.0    16744
 7003.0    11635
 7005.0     3192
 7002.0     2863
 7007.0     2421
 7006.0     2195
 Name: count, dtype: int64,
 SEX
 2    555221
 1    444068
 9       575
 0       136
 Name: count, dtype: int64,
 ETHNOS
 A     676506
 Z      96432
 C      49125
 99     47386
 S      21551
 H      19621
 J      18140
 N      14199
 L      13286
 M       8983
 K       6499
 B       6436
 G       5907
 P       5693
 D       3473
 F       2605
 R       2407
 E       1751
 Name: count, dtype: int64)

Given the above, to build a usable analysis table, I will:
- Collapse to one row per spell, where a spell is defined by the unique combination of (patient, admission date, discharge date).
- Recalculate length of stay (LOS) from these dates.
- Compute the mode of primary diagnosis, ethnicity, and sex per spell (deterministic tie-break).
- Flag any emergency admission within the spell.
- Remove LSOA codes that start with W01 as those are for Wales. The IMD mapping table for deprivation deciles is only for England.
- Join deprivation (IMD) to APC table and define IMD quintiles.
- Filter for Diseases of the respiratory system (J00-J99)
- Keep only Male (1) and Female (2) sex groups.
- Map ethnicity codes to their descriptions.
- Remove infant ages (7001-7007).
- Create a stable spell ID (patient|adm|dis) for downstream analysis.
- Treat implausible dates (e.g. < 1900) as missing before calculations.

tools\repair_synthetic_hes.py runs this cleaning process an returns apc_clean.parquet.

### __DQ Checks Post-cleanse__

In [7]:
df = pd.read_parquet("../data/processed/apc_clean.parquet")

Review data for patient_id _TEST0ESTu849rLXefV1OJZb6lI73YTHH_ after cleansing

In [8]:
df[df["patient_id"] == 'TEST0ESTu849rLXefV1OJZb6lI73YTHH'].sort_values(by=["adm", "dis"])

,patient_id,adm,dis,n_episodes,los_days,any_emerg,imd_quintile,primary_diag,ethnicity,sex,age,spell_id,ethnicity_group,age_band_quinary,is_respiratory,respiratory_group
14709,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-04-10,2021-04-10,1,1.0,False,3,J181,A,2,37,TEST0ESTu849rLXefV1OJZb6lI73YTHH|2021-04-10|20...,White,35-39,True,Pneumonia
139351,TEST0ESTu849rLXefV1OJZb6lI73YTHH,2021-04-28,2021-05-17,1,20.0,False,2,J181,A,2,37,TEST0ESTu849rLXefV1OJZb6lI73YTHH|2021-04-28|20...,White,35-39,True,Pneumonia

Although the patient_id is identical, each row will represent a distinct spell and will be analysed individually.

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145305 entries, 0 to 145304
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   patient_id         145305 non-null  object
 1   adm                145305 non-null  datetime64[ns]
 2   dis                145305 non-null  datetime64[ns]
 3   n_episodes         145305 non-null  int64
 4   los_days           145305 non-null  float64
 5   any_emerg          145305 non-null  bool
 6   imd_quintile       142510 non-null  Int8
 7   primary_diag       145305 non-null  object
 8   ethnicity          145305 non-null  category
 9   sex                145305 non-null  category
 10  age                145305 non-null  Int16
 11  spell_id           145305 non-null  string
 12  ethnicity_group    145305 non-null  category
 13  age_band_quinary   145305 non-null  category
 14  is_respiratory     145305 non-null  boolean
 15  respiratory_group  145305 non-null  category
dtypes: Int16(1), Int8(1), bool(1), boolean(1), category(5), datetime64[ns](2), float64(1), int64(1), object(2), string(1)
memory usage: 9.6+ MB

In [10]:
df.describe()

,adm,dis,n_episodes,los_days,imd_quintile,age
count,145305,145305,145305.000000,145305.000000,142510.0,145305.0
mean,2020-03-28 13:41:08.305977344,2020-06-22 18:39:01.133477888,1.000110,87.206861,2.884871,55.315213
min,2018-06-07 00:00:00,2019-04-01 00:00:00,1.000000,1.000000,1.0,1.0
25%,2019-06-05 00:00:00,2019-10-17 00:00:00,1.000000,2.000000,2.0,35.0
50%,2020-04-26 00:00:00,2020-06-26 00:00:00,1.000000,53.000000,3.0,58.0
75%,2021-04-02 00:00:00,2021-04-12 00:00:00,1.000000,149.000000,4.0,74.0
max,2021-06-25 00:00:00,2021-06-30 00:00:00,2.000000,696.000000,5.0,120.0
std,NaN,NaN,0.010493,92.686794,1.406836,25.330179

In [11]:
# Respiratory admissions only check
df[df["is_respiratory"] != True]

Empty DataFrame
Columns: [patient_id, adm, dis, n_episodes, los_days, any_emerg, imd_quintile, primary_diag, ethnicity, sex, age, spell_id, ethnicity_group, age_band_quinary, is_respiratory, respiratory_group]
Index: []

In [12]:
# Nulls per column
df.isna().mean()

patient_id           0.000000
adm                  0.000000
dis                  0.000000
n_episodes           0.000000
los_days             0.000000
any_emerg            0.000000
imd_quintile         0.019235
primary_diag         0.000000
ethnicity            0.000000
sex                  0.000000
age                  0.000000
spell_id             0.000000
ethnicity_group      0.000000
age_band_quinary     0.000000
is_respiratory       0.000000
respiratory_group    0.000000
dtype: float64

In [13]:
# duplciate spell id check
patient_spell_count = df.groupby("spell_id", as_index=False).agg(n_id=("spell_id", "count"))
patient_spell_count[patient_spell_count["n_id"] > 1]

Empty DataFrame
Columns: [spell_id, n_id]
Index: []